---
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Restart kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: true