[masters]
masterone.example.com   ansible_host=192.168.56.41
mastertwo.example.com   ansible_host=192.168.56.42

[workers]
workerone.example.com   ansible_host=192.168.56.51
workertwo.example.com   ansible_host=192.168.56.52

[loadbalancer]
lbone.example.com  ansible_host=192.168.56.61

# -------- Cluster Groups --------

[k8s_cluster:children]
masters
workers