[masters]
masterone.example.com   ansible_host=192.168.29.41
mastertwo.example.com   ansible_host=192.168.29.42

[workers]
workerone.example.com   ansible_host=192.168.29.51
workertwo.example.com   ansible_host=192.168.29.52

[loadbalancer]
lbone.example.com  ansible_host=192.168.29.61

# -------- Cluster Groups --------

[k8s_cluster:children]
masters
workers