all:
  children:
    masters:
      hosts:
        masterone.example.com:
          ansible_host: 192.168.56.41
          short_name: masterone
          alt_names:
            - masterone
            - masterone.example.com

        mastertwo.example.com:
          ansible_host: 192.168.56.42
          short_name: mastertwo
          alt_names:
            - mastertwo
            - mastertwo.example.com

    workers:
      hosts:
        workerone.example.com:
          ansible_host: 192.168.56.51
          short_name: workerone
          alt_names:
            - workerone
            - workerone.example.com

        workertwo.example.com:
          ansible_host: 192.168.56.52
          short_name: workertwo
          alt_names:
            - workertwo
            - workertwo.example.com

    loadbalancer:
      hosts:
        lbone.example.com:
          ansible_host: 192.168.56.61
          short_name: lbone
          alt_names:
            - lbone
            - lbone.example.com

    k8s_cluster:
      children:
        masters:
        workers: