---
- name: Slurp CA cert
  slurp:
    src: "{{ kc.ca_path }}"
  register: slurped_ca
  when: kc.embed_certs
  delegate_to: "{{ node }}"

- name: Slurp client cert
  slurp:
    src: "{{ kc.cert_path }}"
  register: slurped_cert
  when: kc.embed_certs
  delegate_to: "{{ node }}"

- name: Slurp client key
  slurp:
    src: "{{ kc.key_path }}"
  register: slurped_key
  when: kc.embed_certs
  delegate_to: "{{ node }}"

- name: Generate kubeconfig
  template:
    src: kubeconfig.j2
    dest: "{{ kc.dest }}"
    owner: root
    group: root
    mode: '0600'
  become: true
  delegate_to: "{{ node }}"