---
- ansible.builtin.import_tasks: path.yml
  tags: [kubeconfig, path_generate]

- name: Generate component kubeconfigs
  ansible.builtin.import_tasks: generate.yml
  tags: [kubeconfig, kubeconfig_generate]

- name: Generate kubelet kubeconfigs
  ansible.builtin.import_tasks: kubelet.yml
  tags: [kubeconfig, kubeconfig_kubelet]

- name: Distribute kubeconfigs
  ansible.builtin.import_tasks: distribute.yml
  tags: [kubeconfig, kubeconfig_distribute]