---
- name: Generating {{ item.value.name }}.key...
  community.crypto.openssl_privatekey:
    path: "{{ pki_local_dir }}/{{ item.value.name }}.key"
    size: "{{ item.value.key_size }}"
    type: "{{ item.value.key_type }}"
    mode: '0600'

- name: Generate csr for {{ item.value.organizational_unit }}...
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ pki_local_dir }}/{{ item.value.name }}.key"
    common_name: "{{ item.value.common_name }}"
    country_name: "{{ item.value.country }}"
    state_or_province_name: "{{ item.value.state }}"
    locality_name: "{{ item.value.locality }}"
    organization_name: "{{ item.value.organization }}"
    organizational_unit_name: "{{ item.value.organizational_unit }}"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage: "{{ item.value.key_usage }}"
    key_usage_critical: true
  register: ca_csr

- name: Generate self-signed {{ item.value.name }}.crt...
  community.crypto.x509_certificate:
    path: "{{ pki_local_dir }}/{{ item.value.name }}.crt"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ pki_local_dir }}/{{ item.value.name }}.key"
    provider: selfsigned
    selfsigned_not_after: "+{{ item.value.expiry }}d"
    selfsigned_not_before: "-1d"
    mode: '0644'